version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "EleicaoAvivApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-9yjdr2e9o3hv"
s3_prefix = "EleicaoAvivApi"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
