AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for cashflow-api
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'Content-Type, Authorization'"
      AllowOrigin: "'*'"

Resources:
  EleicaoAvivApi:
      Type: AWS::Serverless::Api
      Properties:
        Name: Eleição AVIV API
        StageName: prod
        Auth:
          AddDefaultAuthorizerToCorsPreflight: false
          DefaultAuthorizer: MyLambdaTokenAuthorizer
          Authorizers:
            MyLambdaTokenAuthorizer:
              FunctionArn: !GetAtt AuthHandlerFunction.Arn

  AppSettingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: eleicao_aviv_settings
        BillingMode: PAY_PER_REQUEST 
        AttributeDefinitions:
            -
              AttributeName: "config_name"
              AttributeType: "S"
            -
              AttributeName: "config_value"
              AttributeType: "S"
        KeySchema:
            -
              AttributeName: "config_name"
              KeyType: "HASH"
            -
              AttributeName: "config_value"
              KeyType: "RANGE"
       
  AuthHandlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: app
      Handler: ./src/functions/authHandlerFunction.handler
      Runtime: nodejs14.x
      MemorySize: 256

  TestFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: app/dist
      Handler: ./functions/testFunction.lambdaHandler
      Runtime: nodejs14.x
      MemorySize: 256
      Events:
        ApiGatewayEvent:
          Type: Api 
          Properties:
            Path: /test
            Method: get
            RestApiId: !Ref EleicaoAvivApi
      
  

  
